version: '3.8'


services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
environment:
  - DB_HOST=${DB_HOST}
  - DB_USER=${DB_USER}
  - DB_PASS=${DB_PASS}
  - DB_NAME=${DB_NAME}

