services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8066:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8077:80"
    volumes:
      - ./Backend:/var/www/html