services:
  front:
    build:
      context: ./Frontend
      dockerfile: ../Dockerfile
    ports:
      - "8066:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
      dockerfile: ../Dockerfile
    ports:
      - "8077:80"
    volumes:
      - ./Backend:/var/www/html